set(_CATKIN_CURRENT_PACKAGE "fixed_msg")
set(fixed_msg_VERSION "0.0.0")
set(fixed_msg_MAINTAINER "li <li@todo.todo>")
set(fixed_msg_PACKAGE_FORMAT "2")
set(fixed_msg_BUILD_DEPENDS "geometry_msgs" "message_generation" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(fixed_msg_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(fixed_msg_BUILDTOOL_DEPENDS "catkin")
set(fixed_msg_BUILDTOOL_EXPORT_DEPENDS )
set(fixed_msg_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(fixed_msg_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(fixed_msg_TEST_DEPENDS )
set(fixed_msg_DOC_DEPENDS )
set(fixed_msg_URL_WEBSITE "")
set(fixed_msg_URL_BUGTRACKER "")
set(fixed_msg_URL_REPOSITORY "")
set(fixed_msg_DEPRECATED "")