(cl:in-package fixed_msg-msg)
(cl:export '(STAMP-VAL
          STAMP
          VERSION-VAL
          VERSION
          DEVICE_ID-VAL
          DEVICE_ID
          POS_X-VAL
          POS_X
          POS_Y-VAL
          POS_Y
          POS_Z-VAL
          POS_Z
          QUA_X-VAL
          QUA_X
          QUA_Y-VAL
          QUA_Y
          QUA_Z-VAL
          QUA_Z
          QUA_W-VAL
          QUA_W
          HORIZONTAL-VAL
          HORIZONTAL
          VERTICAL-VAL
          VERTICAL
          TEMPERATURE-VAL
          TEMPERATURE
          V_FORMAT-VAL
          V_FORMAT
          V_DATA-VAL
          V_DATA
))