// Generated by gencpp from file fixed_msg/cp_control.msg
// DO NOT EDIT!


#ifndef FIXED_MSG_MESSAGE_CP_CONTROL_H
#define FIXED_MSG_MESSAGE_CP_CONTROL_H

#include <ros/service_traits.h>


#include <fixed_msg/cp_controlRequest.h>
#include <fixed_msg/cp_controlResponse.h>


namespace fixed_msg
{

struct cp_control
{

typedef cp_controlRequest Request;
typedef cp_controlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cp_control
} // namespace fixed_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fixed_msg::cp_control > {
  static const char* value()
  {
    return "be6cabd355b563d374071eb0d114fd3d";
  }

  static const char* value(const ::fixed_msg::cp_control&) { return value(); }
};

template<>
struct DataType< ::fixed_msg::cp_control > {
  static const char* value()
  {
    return "fixed_msg/cp_control";
  }

  static const char* value(const ::fixed_msg::cp_control&) { return value(); }
};


// service_traits::MD5Sum< ::fixed_msg::cp_controlRequest> should match
// service_traits::MD5Sum< ::fixed_msg::cp_control >
template<>
struct MD5Sum< ::fixed_msg::cp_controlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fixed_msg::cp_control >::value();
  }
  static const char* value(const ::fixed_msg::cp_controlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fixed_msg::cp_controlRequest> should match
// service_traits::DataType< ::fixed_msg::cp_control >
template<>
struct DataType< ::fixed_msg::cp_controlRequest>
{
  static const char* value()
  {
    return DataType< ::fixed_msg::cp_control >::value();
  }
  static const char* value(const ::fixed_msg::cp_controlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fixed_msg::cp_controlResponse> should match
// service_traits::MD5Sum< ::fixed_msg::cp_control >
template<>
struct MD5Sum< ::fixed_msg::cp_controlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fixed_msg::cp_control >::value();
  }
  static const char* value(const ::fixed_msg::cp_controlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fixed_msg::cp_controlResponse> should match
// service_traits::DataType< ::fixed_msg::cp_control >
template<>
struct DataType< ::fixed_msg::cp_controlResponse>
{
  static const char* value()
  {
    return DataType< ::fixed_msg::cp_control >::value();
  }
  static const char* value(const ::fixed_msg::cp_controlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIXED_MSG_MESSAGE_CP_CONTROL_H
