// Generated by gencpp from file fixed_msg/cp_controlResponse.msg
// DO NOT EDIT!


#ifndef FIXED_MSG_MESSAGE_CP_CONTROLRESPONSE_H
#define FIXED_MSG_MESSAGE_CP_CONTROLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fixed_msg
{
template <class ContainerAllocator>
struct cp_controlResponse_
{
  typedef cp_controlResponse_<ContainerAllocator> Type;

  cp_controlResponse_()
    : result(0)  {
    }
  cp_controlResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::fixed_msg::cp_controlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fixed_msg::cp_controlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct cp_controlResponse_

typedef ::fixed_msg::cp_controlResponse_<std::allocator<void> > cp_controlResponse;

typedef boost::shared_ptr< ::fixed_msg::cp_controlResponse > cp_controlResponsePtr;
typedef boost::shared_ptr< ::fixed_msg::cp_controlResponse const> cp_controlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fixed_msg::cp_controlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fixed_msg::cp_controlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fixed_msg::cp_controlResponse_<ContainerAllocator1> & lhs, const ::fixed_msg::cp_controlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fixed_msg::cp_controlResponse_<ContainerAllocator1> & lhs, const ::fixed_msg::cp_controlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fixed_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fixed_msg::cp_controlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fixed_msg::cp_controlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fixed_msg::cp_controlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fixed_msg::cp_controlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fixed_msg::cp_controlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fixed_msg::cp_controlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fixed_msg::cp_controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::fixed_msg::cp_controlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::fixed_msg::cp_controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fixed_msg/cp_controlResponse";
  }

  static const char* value(const ::fixed_msg::cp_controlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fixed_msg::cp_controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
"\n"
;
  }

  static const char* value(const ::fixed_msg::cp_controlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fixed_msg::cp_controlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cp_controlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fixed_msg::cp_controlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fixed_msg::cp_controlResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIXED_MSG_MESSAGE_CP_CONTROLRESPONSE_H
