mqtt:
  client_name: tio_bridge_115
  client:
    protocol: 4      # MQTTv311
  connection:
    host: 192.168.1.35
    port: 1883
    keepalive: 60
  private_path: device/001
  account:
    username: ydrobot
    password: 123qweasd
bridge:
    # ping pong
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Bool
    topic_from: /ping
    topic_to: ping
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:Bool
    topic_from: ping
    topic_to: /pong
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: undistort_service_msgs.msg:PosedImage
    topic_from: /infrared/undistorted
    topic_to: infrared/undistorted
  - factory: mqtt_bridge.bridge:MqttToStrBridge
    msg_type: std_msgs.msg:String
    topic_from: /ydcloud/gw/3/iot/task/data/down
    topic_to: /tio/task/data/down
  - factory: mqtt_bridge.bridge:MqttToStrBridge
    msg_type: std_msgs.msg:String
    topic_from: /ydcloud/gw/3/iot/task/command/down
    topic_to: /tio/task/command/down
  - factory: mqtt_bridge.bridge:StrToMqttBridge
    msg_type: std_msgs.msg:String
    topic_from: /tio/control/web_status
    topic_to: /ydcloud/gw/3/iot/task/status/up
  - factory: mqtt_bridge.bridge:MqttToStrBridge
    msg_type: std_msgs.msg:String
    topic_from: /ydcloud/gw/3/iot/task/status/up
    topic_to: /tio/control/web_status/pong
  - factory: mqtt_bridge.bridge:StrToMqttBridge
    msg_type: std_msgs.msg:String
    topic_from: /tio/control/web_progress
    topic_to: /ydcloud/gw/3/iot/task/progress/up
  - factory: mqtt_bridge.bridge:MqttToStrBridge
    msg_type: std_msgs.msg:String
    topic_from: /ydcloud/gw/3/iot/task/progress/up
    topic_to: /tio/control/web_progress/pong
